import React from "react";
import "./Policy.css";

function Policy() {
    return (
        <div className="policy-box">
            <h1 className="text-center mb-20">Con Edison Privacy Policy</h1>
            <p>Your privacy is important to us, so we protect the information we collect from you while doing business together.</p>
            <p>We obtain this information in several ways: through our websites, apps, and social media pages; your use of electric, gas and/or steam services; any devices and technologies related to any energy efficiency, demand management, distributed generation or other initiatives or programs we may offer to you from time to time; third-party sources, social media platforms, and in-person, phone, email, text or written correspondence with you.</p>
            <p>This information may include your name, account number, home or business address, email address, telephone number, energy use data (including but not limited to smart meter readings), location information, or other information that is specific to you as our customer or that you otherwise elect to share with us.</p>
            <p>At the end of this Privacy Statement, we provide you with the opportunity to choose regarding our use and disclosure of your Customer Information to third-parties for marketing purposes. Customer Information includes your name, account number, home or business address, email address, and telephone number.</p>

            <h3 className="mt-40 fw-bold">How We May Collect and Use Information</h3>
            <p>We gather and use information to do business with you, including sending you bills, letting you know about products and services we offer, and addressing your questions or concerns.</p>
            <p>We may use information from programs in which you voluntarily participate. Some of these programs have additional rules, which may contain additional conditions regarding how we may use and disclose your information. We recommend that you read any such rules carefully.</p>
            <p>We may use your information for business purposes, such as data analysis, audits, fraud monitoring and prevention, developing new product offerings and services, enhancing, improving or modifying our product offerings and services, identifying trends in energy use, developing and promoting programs and initiatives to encourage more efficient energy use and to manage demand for electricity, determining the effectiveness of our programs and promotional campaigns, and operating and expanding our business activities.</p>
            <p>We may use information as we believe to be necessary or appropriate, to: (a) comply with requirements or directives of our governing regulatory agencies including, among others, the New York State Public Service Commission, the New Jersey Board of Public Utilities, and the Federal Energy Regulatory Commission; (b) respond to requests from government or judicial authorities; (c) enforce our terms and conditions of service and applicable tariffs; (d) protect our operations or those of our affiliates; (e) protect our rights, privacy, safety or property, and/or that of our affiliates, you or others; and (f) allow us to pursue available remedies or limit the damages that we may sustain. We also may use your information to send or serve marketing communications, offers, and promotions that may be of interest, including on social media platforms.</p>
            <p>We send occasional online surveys to gather information about your use of, and your opinion about, our programs and services, our energy related product offerings, and our websites and apps. Participation in our online surveys is voluntary. If you choose to participate, the information you provide will be used to improve our websites and apps and the programs, products and services we offer to you.</p>


            <h3 className="mt-40 fw-bold">How We May Share Information</h3>
            <p>We may share information with our service providers or contractors in order to help us to do business with you, including processing payments, answering questions, developing and promoting programs, product offerings or services, or fulfilling your requests for a product or service.</p>
            <p>We may share information with third-parties to permit them to send marketing communications or information about products and services that may be of interest, consistent with your choices. Also consistent with your choices, we may also share information with third-parties who provide energy-related products and services.</p>
            <p>We may need to share information as we believe necessary and appropriate to: (a) comply with the requirements or directives of our governing regulatory agencies including, among others, the New York State Public Service Commission, the New Jersey Board of Public Utilities, and the Federal Energy Regulatory Commission; (b) respond to requests from government or judicial authorities; (c) enforce our terms and conditions of service and applicable tariffs; (d) protect our operations or those of our affiliates; (e) protect our rights, privacy, safety or property, and/or that of our affiliates, you or others; and (f) allow us to pursue available remedies or limit the damages that we may sustain. We also may use your information to send marketing communications, offers, and promotions that may be of interest.</p>
            <p>We may disclose information to a third-party in the event of any reorganization, merger, sale, joint venture, assignment, transfer or other disposition of all or any portion of our business, assets or stock (including in connection with any bankruptcy or similar proceedings).</p>

            <h3 className="mt-40 fw-bold">Other Information We May Collect, Use, and Disclose</h3>
            <p>We use software to automatically collect other information that does not directly identify you. This information, such as the name of the domain or IP address where you access the Internet, the date and time when you access any of our websites, and the information that you view while using our services, is typically used for statistical purposes to help us to evaluate and improve our product offerings, services, and websites and apps, diagnose and correct technical problems, and detect fraud or other illegal activity and protect our systems.</p>
            <p>We may also aggregate information so that it does not identify you or any other customer or user (for example, we may aggregate information to calculate the percentage of our customers who have a particular telephone area code). Please note that we may use and disclose this other information or aggregated information for any purpose, except where we are required to do otherwise under applicable law.</p>
            <p>We may collect the physical location of the device you use to communicate with us. We may use your device's physical location to provide you with personalized location-based services and content. We may also share your device's physical location, combined with information about what advertisements you viewed and other information we collect, with our marketing partners to enable them to provide you with more personalized content. In some instances, you may allow or deny such uses and/or sharing of your device's location, but if you choose to deny such uses and/or sharing, we and/or our marketing partners may not be able to provide you with the applicable personalized services and content.</p>

            <h3 className="mt-40 fw-bold">Security</h3>
            <p>Con Edison has implemented policy guidelines and reasonable organizational, technical and administrative measures to help safeguard your information, from unauthorized access or improper use. Unfortunately, no data transmission or storage system can be guaranteed to be 100% secure. If you believe your interaction with us is no longer secure, please contact us right away.</p>
            <p>Con Edison's equipment and services are a part of our nation’s critical infrastructure; we are therefore vigilant about protecting our systems. Any electronic correspondence that you send to Con Edison, including email or any forms that you complete and transmit through our websites, may be monitored for suspected illegal activity and/or shared with regulatory, public or government agencies.</p>

            <h3 className="mt-40 fw-bold">Special Notes</h3>
            <p>Links: This Privacy Statement does not address, and we are not responsible for, the privacy, information or other practices of any third-parties, including any third-party operating any site or service linked to our websites. The inclusion of a link on our websites does not imply endorsement of the linked site or service by us or our affiliates. Please note that we are not responsible for the collection, usage and disclosure policies and practices (including the data security practices) of other organizations, such as Facebook, Apple, Google, Microsoft, RIM, or any other app developer, app provider, social media platform provider, web browser provider, operating system provider, wireless service provider or device manufacturer, including any information you disclose to other organizations through or in connection with our apps or social media accounts.</p>
        </div>
    );
};

export default Policy;